version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    container_name: mydb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "shop"
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_PASSWORD: "1234"
